apiVersion: v1
kind: Service
metadata:
  name: jhineye-message-publisher
  labels:
    app: jhineye-message-publisher
spec:
  selector:
    app: jhineye-message-publisher
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.containerPort }}
